spring:
  application:
    name: SERVICE-INGESTIONVIDEO
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/

logging:
  level:
    ma.emsi.ingestionvideo: DEBUG