services:
  mysql:
    container_name: "rs-mysql"
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - rs-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rsdb
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-vol:

networks:
  rs-net:
    name: rs-net
    driver: bridge