spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true              # dynamic routes from Eureka
          lower-case-service-id: true
      routes:
        - id: ingestion
          uri: lb://SERVICE-INGESTIONVIDEO
          predicates:
            - Path=/ingestion/**
          filters:
            - StripPrefix=1

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/
