spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ingestion
          uri: lb://SERVICE-INGESTIONVIDEO
          predicates:
            - Path=/ingestion/**
          filters:
            - StripPrefix=1

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/