services:
  service-eureka:
    container_name: eureka-server
    build:
      context: ./eurekaServer
    env_file:
      - .env
    networks:
      - rs-net
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${EUREKA_SERVER_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api-gateway:
    container_name: api-gateway
    build:
      context: ./apiGateway
    env_file:
      - .env
    networks:
      - rs-net
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      service-eureka:
        condition: service_healthy   # Wait for Eureka healthcheck
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${GATEWAY_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  db-ingestion:
    container_name: db-ingestion
    image: mysql:8.0
    networks:
      - rs-net
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
    # No ports: means DB is internal-only (headless)
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
    restart: always

  service-ingestion:
    container_name: service-ingestion
    build:
      context: ./ingestionVideo
    networks:
      - rs-net
    env_file:
      - .env
    depends_on:
      service-eureka:
        condition: service_healthy
      db-ingestion:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${INGESTION_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  fe:
    container_name: fe
    build:
      context: ../fe        # path to your Angular project with Dockerfile
    ports:
      - "${END_USER_PORT}:80"          # host:container (Nginx serves on 80 inside)
    restart: always

  db-sonarqube:
    image: postgres:15
    container_name: db-sonarqube
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_pgdata:/var/lib/postgresql/data
    networks:
      - rs-net
    restart: always

  service-sonarqube:
    image: sonarqube:community
    container_name: service-sonarqube
    depends_on:
      - db-sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "${SONARQUBE_PORT}:9000"          # access UI at http://localhost:9000
    networks:                             # user: sonar - pwd: Sonar100%sonar
      - rs-net
    restart: always

  service-jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: service-jenkins
    user: root
    ports:
      - "${JENKINS_PORT}:8080"          # Jenkins UI at http://localhost:9090
      - "50000:50000"                   # JNLP agents (optional)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # allow Jenkins to run docker/compose
    networks:
      - rs-net
    restart: always

volumes:
  mysql_data:
  sonarqube_pgdata:
  jenkins_home:

networks:
  rs-net:
    name: rs-net
    driver: bridge